#!/bin/bash
LOCATION=$HOME/.ssh
create_ssh() { #optional
  ssh-keygen -C $(whoami)
}

configssh() {
  mkdir -p "$LOCATION/.ssh"
  touch "$LOCATION/config"
  echo "Host $1
   Hostname $2
   User $3
  " >>"$LOCATIONconfig"
}

# error handling
set -eou pipefail

if ! type ssh >/dev/null 2>&1 || ! type sshd >/dev/null 2>&1; then
  echo "ssh not installed"
  echo "wait ssh installing..."
  pkg update -y >/dev/null 2>&1 || sudo apt update -y >/dev/null 2>&1
  if sudo apt install openssh-server -y >/dev/null 2>&1 || pkg install openssh; then
    echo "ssh successfully installed!."
  else
    echo "ssh installtion failed"
    echo "Try to install manually using command sudo apt install openssh-server"
    echo "for termux use: pkg install openssh"
    exit 1
  fi
fi

## Menu
echo "|------ MENU ------|"
echo "[1]:- Press to generate key "
echo "[2]:- Press to make the config file"
echo "[3]:- Press to exit"
read -p "Enter the choice: " CHOICE
if [[ $CHOICE == "1" ]]; then
  create_ssh
elif [[ $CHOICE == "2" ]]; then
  read -p "Enter host: shell name: " host
  read -p "Enter hostname ip or host url: " hostname
  read -p "Enter the username of shell: " username
  configssh "$host" "$hostname" "$username"
else
  echo "invalid choice"
fi
